(add-to-list 'load-path "~/.emacs.d/elisp/async")
(add-to-list 'load-path "~/.emacs.d/elisp/helm")
(require 'helm-config)

(global-set-key (kbd "M-x") 'helm-M-x)
(global-set-key (kbd "C-c h") 'helm-mini)
(global-set-key (kbd "C-x C-f") 'helm-find-files)
(global-set-key (kbd "M-y") 'helm-show-kill-ring)
(global-set-key (kbd "M-s") 'helm-occur)
(global-set-key (kbd "C-x b") 'helm-for-files)
(global-set-key (kbd "C-]") 'helm-ls-git-ls)
(global-set-key (kbd "C-c g") 'helm-git-grep)
